_target_: emgen.generative_model.diffusion.diffusion_model_arch.LinearArch
device: ${device}
data_dim: 2
emb_size: 128
input_emb: sinusoidal
time_emb: sinusoidal
hidden_size: 128
hidden_layers: 3
weights: null