
_target_: emgen.generative_model.diffusion.diffusion_model.DiffusionModel
device: cuda

noise_scheduler:
  _target_: emgen.generative_model.diffusion.noise_scheduler.NoiseScheduler
  device: ${device}
  num_timesteps: 100
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: cosine
  deterministic_sampling: false
  eta: 0 # DDIM stochasticity

diffusion_arch: # or unet, unet1d
  _target_: emgen.generative_model.diffusion.diffusion_model_arch.UNetArch
  device: ${device}
  emb_size: 128
  time_emb: sinusoidal
  in_channels: 1
  base_channels: 64
  num_down: 2
  weights: null
  

dataset:
  _target_: emgen.dataset.mnist.MNISTDataset
  train: true

train:
  train_batch_size: 32
  eval_batch_size: 32
  num_epochs: 100
  learning_rate: 0.001

  save_images_step: 1
  no_of_diff_samples_to_save: 36
